export const shoes = [
  {
    id: 1,
    type: "sneakers",
    brand: "nike",
    model: "airforce",
    shoes: "midnoone",
    sizes: JSON.stringify({ 36: 10, 37: 10 }),
    season: ["summer"],
    colors: ["blue", "black"],
    price: 10000,
    img: [],
    description: "",
  },
  {
    id: 2,
    type: "sneakers",
    brand: "nike",
    model: "airforce",
    shoes: "pokemon",
    sizes: JSON.stringify({ 36: 10, 37: 10 }),
    season: [],
    colors: [],
    price: 10000,
    img: [],
    description: "",
  },
  {
    id: 3,
    type: "sneakers",
    brand: "nike",
    model: "airforce",
    shoes: "lighter",
    sizes: JSON.stringify({ 36: 10, 37: 10 }),
    season: ["summer"],
    colors: ["blue", "black"],
    price: 10000,
    img: [],
    description: "",
  },
  {
    id: 4,
    type: "sneakers",
    brand: "nike",
    model: "airforce",
    shoes: "darkgrow",
    sizes: JSON.stringify({ 36: 10, 37: 10, 39: 0 }),
    season: ["summer"],
    colors: ["red", "blue"],
    price: 10000,
    img: [],
    description: "",
  },
  {
    id: 5,
    type: "sneakers",
    brand: "nike",
    model: "airforce",
    shoes: "skeleton",
    sizes: JSON.stringify({ 36: 10, 37: 10 }),
    season: ["summer"],
    colors: ["blue", "black"],
    price: 10000,
    img: [],
    description: "",
  },
];
